// Generated by CoffeeScript 1.4.0
(function() {

  VKAudio.BitRater = (function() {

    function BitRater(audio) {
      this.audio = audio;
    }

    BitRater.prototype.requestContentLength = function() {
      var xhr;
      xhr = new XMLHttpRequest();
      xhr.onreadychange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
          return this.calculateBitRate(xhr.getResponseHeader("Content-Length"));
        }
      };
      xhr.open("HEAD", this.audio.url, true);
      return xhr.send(null);
    };

    BitRater.prototype.calculateBitRate = function(contentLength) {
      var bitRate;
      return bitRate = ((size * 8) / mp3.duration / 1000).toFixed();
    };

    return BitRater;

  })();

}).call(this);
