// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App.Bitrater = (function() {

    function Bitrater() {
      this.getBitrate = __bind(this.getBitrate, this);

      this._requestContentLength = __bind(this._requestContentLength, this);

    }

    Bitrater.prototype._requestContentLength = function(event) {
      var audioUrl, xhr,
        _this = this;
      audioUrl = event.message.url;
      xhr = new XMLHttpRequest();
      xhr.onreadystatechange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
          return _this._calculateBitrate(event, xhr.getResponseHeader("Content-Length"));
        }
      };
      xhr.open("HEAD", audioUrl, true);
      return xhr.send(null);
    };

    Bitrater.prototype._calculateBitrate = function(event, size) {
      var audio, bitrate;
      audio = event.message;
      bitrate = ((size * 8) / audio.duration / 1000).toFixed();
      return event.target.page.dispatchMessage("setBitrate", {
        bitrate: bitrate,
        id: audio.id
      });
    };

    Bitrater.prototype.getBitrate = function(event) {
      return this._requestContentLength(event);
    };

    return Bitrater;

  })();

}).call(this);
