// Generated by CoffeeScript 1.4.0
(function() {

  VKAudio.Broadcaster = (function() {

    function Broadcaster() {
      this.observers = new Object;
    }

    Broadcaster.prototype.addEventHandler = function(type, handler) {
      if (!this.observers[type]) {
        this.observers[type] = new Array;
      }
      return this.observers[type].push(handler);
    };

    Broadcaster.prototype.broadcast = function(type, message) {
      return _.each(this.observers[type], function(func) {
        return func(type, message);
      });
    };

    return Broadcaster;

  })();

}).call(this);
