// Generated by CoffeeScript 1.4.0
(function() {
  var Router, broadcaster, router;

  Router = (function() {

    function Router(bitRater, lastFM) {
      this.bitRater = bitRater;
      this.lastFM = lastFM;
    }

    Router.prototype.routeMessage = function(message) {
      var cmd;
      cmd = message.name;
      switch (cmd) {
        case "getSettings":
          return this._getSettings(message);
        case "getBitrate":
          return this._getBitrate(message);
        case "getLastFMToken":
          return this._getLastFMToken(message);
        case "setLasfFMPlayingNow":
          return this._setLasfFMPlayingNow(message);
        case "scrobble":
          return this._scrobble(message);
        default:
          return this._log(message);
      }
    };

    Router.prototype._getSettings = function(message) {};

    Router.prototype._getBitrate = function(message) {};

    Router.prototype._getLastFMToken = function(message) {};

    Router.prototype._setLasfFMPlayingNow = function(message) {};

    Router.prototype._scrobble = function(message) {};

    Router.prototype._log = function(message) {
      return console.log(message);
    };

    return Router;

  })();

  broadcaster = new VKAudio.Broadcaster();

  router = new Router(new VKAudio.BitRater(), new VKAudio.LastFM());

  safari.application.addEventListener("message", router.routeMessage, false);

}).call(this);
