// Generated by CoffeeScript 1.4.0
(function() {
  var lastFM, routeMessage;

  lastFM = new LastFM();

  safari.application.addEventListener("message", routeMessage, false);

  routeMessage = function(message) {
    var cmd;
    cmd = message.name;
    switch (cmd) {
      case "getSettings":
        return 0;
      case "getBitrate":
        return 0;
      case "getLastFMToken":
        return 0;
      case "setLasfFMPlayingNow":
        return 0;
      case "scrobble":
        return 0;
      default:
        return console.log("Unknowm command " + cmd);
    }
  };

}).call(this);
