// Generated by CoffeeScript 1.4.0
(function() {
  var VKAudio, VKAudioCollection, audios, insertAfter, route, setBitrate;

  if (window.top === window) {
    VKAudioCollection = (function() {

      function VKAudioCollection() {
        this.audios = new Array;
        this.ids = new Array;
        console.log("VKAudiocollection created");
      }

      VKAudioCollection.prototype.collectNodes = function() {
        return document.getElementsByClassName("play_new");
      };

      VKAudioCollection.prototype.buildObjectsFromNodes = function() {
        var node, vkAudio, _i, _len, _ref, _results;
        this.nodes = this.collectNodes();
        _ref = this.nodes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          node = _ref[_i];
          if (this.ids.indexOf(node.id) === -1) {
            vkAudio = new VKAudio(node);
            this.ids.push(node.id);
            _results.push(this.audios.push(vkAudio));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      VKAudioCollection.prototype.showBitrates = function() {
        var audio, _i, _len, _ref, _results;
        _ref = this.audios;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          audio = _ref[_i];
          _results.push(audio.showBitrate());
        }
        return _results;
      };

      VKAudioCollection.prototype.hideBitrates = function() {
        var audio, _i, _len, _ref, _results;
        _ref = this.audios;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          audio = _ref[_i];
          _results.push(audio.hideBitrate());
        }
        return _results;
      };

      return VKAudioCollection;

    })();
    VKAudio = (function() {

      function VKAudio(node) {
        this.node = node;
        console.log("VKAudio builded");
        this.id = this.node.id;
        this.getBitrate();
      }

      VKAudio.prototype.getBitrate = function() {
        var audioData, audioDuration, audioUrl, inputNode, inputNodeId;
        console.log("enter in getBitrate");
        inputNodeId = this.id.replace("play", "audio_info");
        inputNode = document.getElementById(inputNodeId);
        audioData = inputNode.value.match(/(https?:\/\/.+\.(?:vkontakte\.ru|vk\.com|userapi\.com)\/.*.mp3),([0-9]+)/i);
        audioUrl = audioData[1];
        audioDuration = audioData[2];
        safari.self.tab.dispatchMessage("getBitrate", {
          url: audioUrl,
          duration: audioDuration,
          id: this.id
        });
        return console.log("exit of getBitrate");
      };

      VKAudio.prototype.setBitrate = function(bitrate) {
        this.bitrate = bitrate;
        return console.log("set bitrate");
      };

      VKAudio.prototype.createLink = function() {
        return true;
      };

      VKAudio.prototype.showBitrate = function() {
        var divNode;
        console.log("show bitrate");
        divNode = document.createElement("div");
        divNode.className = "bitrate";
        divNode.innerHTML = "" + this.bitrate + " kbit/s";
        return insertAfter(this.node, divNode);
      };

      VKAudio.prototype.hideBitrate = function() {};

      VKAudio.prototype.setLink = function() {};

      return VKAudio;

    })();
    route = function(event) {
      var cmd;
      cmd = event.name;
      switch (cmd) {
        case "setBitrate":
          return setBitrate(event.message);
      }
    };
    setBitrate = function(audio) {
      var audioIndex;
      audioIndex = audios.ids.indexOf(audio.id);
      return audios.audios[audioIndex].setBitrate(audio.bitrate);
    };
    insertAfter = function(targetNode, newNode) {
      return targetNode.parentNode.insertBefore(newNode, targetNode.nextSibling);
    };
    safari.self.addEventListener("message", route, false);
    audios = new VKAudioCollection;
    audios.buildObjectsFromNodes();
    document.addEventListener("keydown", function(event) {
      if (event.altKey) {
        console.log("alt pressed");
        return audios.showBitrates();
      }
    }, false);
  }

}).call(this);
