// Generated by CoffeeScript 1.4.0
(function() {
  var routeMessage, testTarget;

  if (window.top === window) {
    document.addEventListener("mousemove", function(event) {
      return testTarget(event.target);
    }, false);
    routeMessage = function(message) {
      var cmd;
      cmd = message.name;
      switch (cmd) {
        case "setBitrate":
          return console.log(1);
      }
    };
    testTarget = function(target) {
      if (target.className === "play_new") {
        return console.log("bla-bla-bla");
      }
    };
    safari.self.addEventListener("message", routeMessage, false);
  }

}).call(this);
