// Generated by CoffeeScript 1.4.0
(function() {

  App.LastFM = (function() {

    function LastFM() {}

    LastFM.prototype.constuctor = function() {};

    return LastFM;

  })();

}).call(this);
